nginx:
  build: ./nginx
  links:
    - node1:node1
  ports:
    - "80:80"
node1:
  build: ./node
  links:
    - mongo
  ports:
    - "8080"
mongo:
  build: ./mongodb
  # volumes:
  #   - /data/db:/data/db
  ports:
    - "27017"
